import pandas as pd

student=pd.DataFrame({"name":['Pradeep','Satheesh','Dilip'],'roll_no':[9,10,8],'grade':['B','B','A'],'marks':[80,70,100],'city':['chennai','singapore','America']})
student
#
student.sort_values(by=['marks','grade'0,ascending=[False,True])
#
student.sort_values(by=['marks','grade'],ascending=[False,True],inplace=True)
#
student.reset_index(drop=True,inplace=Truee)
#
code_no=pd.DataFrame({'Code no':['008','007','006']})
student=pd.concat([student,code_no],axis=1)
student
#
req_roll=pd.DataFrame({'roll_no':[8,10]})
student.merge(req_roll,how='right',on='roll_no')
#
student.loc[(student.roll_no==8)]
#
state=pd.DataFrame({'city':['America','chennai','singapore'],'state':['New york','TamilNadu','Dubai']})
student.merge(state,how='left',on='city')
#
student.merge(req_roll,how='right',on='roll_no')
#
placed=pd.DataFrame({'company':['Tesla','Google','Apple'],'package':['10c','8c','9c'],'name':['Dilip','Pradeep','Satheesh']})
student=student.merge(placed,how='outer')
student
#
performance=pd.DataFrame({'performance':['GOOD'],'grade':['B']})
student.merge(performance,how='inner',on='grade')
#
student.marks.mean()
#
student.marks.sum()
#
student.grade.mode()
#
student.grade.value_counts()
#
student.describe()
#
s=student.groupby(['grade'])
s.first()
#
student.max()
#
pd.pivot_table(student,index=[student.roll_no,student.name],values='marks',aggfunc='mean')
#
pd.crosstab(student.name,student.marks)
